version: '4'
services:
  #  mongodb:
  #    image: mongo:latest
  #    container_name: mongodb
  #    ports:
  #      - "27017:27017"
  #    environment:
  #      MONGO_INITDB_ROOT_USERNAME: root
  #      MONGO_INITDB_ROOT_PASSWORD: root
  #      MONGO_INITDB_DATABASE: cooking-recipe-sharing-platform
  #    volumes:
  #      - ./data:/data/db

  app:
    build: src
    image: my-spring-boot-app
    container_name: spring-boot-app
    #    depends_on:
    #      - mongodb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb+srv://root:root@omgsrt.990t6.mongodb.net/?retryWrites=true&w=majority&appName=omgsrt
      SPRING_DATA_MONGODB_DATABASE: ludolify