spring:
  application:
    name: Ludolify

  jwt:
    secret: ${JWT_SECRET}

  data:
    mongodb:
      uri: mongodb+srv://${MONGODB_USER}:${MONGODB_PASSWORD}@omgsrt.990t6.mongodb.net/?retryWrites=true&w=majority&appName=omgsrt
      database: ludolify

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

