spring:
  application:
    name: Ludolify

  jwt:
    secret: ${JWT_SECRET:default_jwt_secret}

  data:
    mongodb:
      username: ${MONGODB_USER:default_user}
      password: ${MONGODB_PASSWORD:default_password}
      uri: mongodb+srv://${MONGODB_USER:${MONGODB_USER:default_user}}:${MONGODB_PASSWORD:${MONGODB_PASSWORD:default_password}}@omgsrt.990t6.mongodb.net/?retryWrites=true&w=majority&appName=omgsrt
      database: ${MONGODB_DATABASE:default_database}

telegram:
  bot:
    name: ${TELEGRAM_BOT_NAME:default_name}
    token: ${TELEGRAM_BOT_TOKEN:default_token}
  chat:
    id: ${TELEGRAM_CHAT_ID:default_id}

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

server:
  port: 8080
